FROM vookimedlo/alpine-gcc:gcc_latest
LABEL maintainer="github@vookimedlo.cz"
LABEL homepage="https://github.com/vookimedlo/docker-images"

RUN apk add --no-cache qt5-qtbase qt5-qtdeclarative qt5-qtxmlpatterns qt5-qtwebengine \
		      qt5-qtbase-dev qt5-qtdeclarative-dev qt5-qtxmlpatterns-dev qt5-qtwebengine-dev
