FROM vookimedlo/alpine-gcc:gcc_latest
LABEL maintainer="github@vookimedlo.cz"
LABEL homepage="https://github.com/vookimedlo/docker-images"

RUN apk add --no-cache qt6-qtbase qt6-qtdeclarative qt6-qtxmlpatterns qt6-qtwebengine \
		      qt6-qtbase-dev qt6-qtdeclarative-dev qt6-qtxmlpatterns-dev qt6-qtwebengine-dev
