FROM vookimedlo/alpine-gcc:gcc_latest
LABEL maintainer="github@vookimedlo.cz"
LABEL homepage="https://github.com/vookimedlo/docker-images"

RUN apk add --no-cache qt6-qtbase  \
		       qt6-qtbase-dev \
	               qt6-qtimageformats \
	               qt6-qtimageformats-dev \
                       qt6-qtsvg \
                       qt6-qtsvg-dev \
                       qt6-qttools \
                       qt6-qttools-dev

