FROM alpine:latest
LABEL maintainer="github@vookimedlo.cz"
LABEL homepage="https://github.com/vookimedlo/docker-images"

RUN apk add --no-cache         \
    clang                      \
    make                       \
    cmake                      \
    git
