FROM debian:stable

RUN apt-get update && apt-get -y install software-properties-common

RUN apt-get update && apt-get -y --allow-unauthenticated install \
    g++   \
    gcc   \
    make  \
    cmake \
    git
