name: Build all docker images via buildah

on:
  workflow_dispatch:
    inputs:
      docker_registry:
        description: 'The target docker image registry'
        required: true
        default: 'ghcr.io'
        type: choice
        options:
          - ghcr.io
          - docker.io
          - quay.io
      alpine:
        description: 'Alpine images'
        default: true
        type: boolean
        required: true
      debian:
        description: 'Debian images'
        default: true
        type: boolean
        required: true
      fedora:
        description: 'Fedora images'
        default: true
        type: boolean
        required: true
      ubuntu:
        description: 'Ubuntu images'
        default: true
        type: boolean
        required: true
jobs:
  build-alpine-images:
    if: ${{ inputs.alpine }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc ]
        version: [ latest ]
    uses: ./.github/workflows/reusable-docker-images-buildah.yml
    with:
      distribution: alpine
      version: ${{ matrix.version }}
      compiler: ${{ matrix.compiler }}
      docker_platforms: linux/amd64
      docker_registry: ${{ inputs.docker_registry }}
    secrets:
      inherit
  build-debian-images:
    if: ${{ inputs.debian }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, clang ]
        version: [ stable, bullseye, bookworm, trixie ]
    uses: ./.github/workflows/reusable-docker-images-buildah.yml
    with:
      distribution: debian
      version: ${{ matrix.version }}
      compiler: ${{ matrix.compiler }}
      docker_platforms: linux/amd64,linux/arm64
      docker_registry: ${{ inputs.docker_registry }}
    secrets: inherit
  build-fedora-images:
    if: ${{ inputs.fedora }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, clang ]
        version: [ stable, 42, 41, 40 ]
    uses: ./.github/workflows/reusable-docker-images-buildah.yml
    with:
      distribution: fedora
      version: ${{ matrix.version }}
      compiler: ${{ matrix.compiler }}
      docker_platforms: linux/amd64,linux/arm64
      docker_registry: ${{ inputs.docker_registry }}
    secrets: inherit
  build-ubuntu-images:
    if: ${{ inputs.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, clang ]
        version: [ jammy, noble, oracular, plucky ]
    uses: ./.github/workflows/reusable-docker-images-buildah.yml
    with:
      distribution: ubuntu
      version: ${{ matrix.version }}
      compiler: ${{ matrix.compiler }}
      docker_platforms: linux/amd64,linux/arm64
      docker_registry: ${{ inputs.docker_registry }}
    secrets: inherit
