name: Docker Images CI via buildah

on:
  workflow_dispatch

jobs:
  build-compilers:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Log in to GitHub Container Registry
          uses: redhat-actions/podman-login@v1
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
        - name: Buildah Action
          uses: redhat-actions/buildah-build@v2
          with:
            image: fedora-gcc-testing-image
            tags: gcc_38 ${{ github.sha }}
            archs: linux/amd64,linux/arm64
            containerfiles: |
              ./gcc/fedora/38/Dockerfile
            build-args: |
              BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
