name: Docker Image [Compilers] CI

on:
  workflow_dispatch

jobs:
  build-compilers:
    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
        - name: Set up QEMU dependency
          uses: docker/setup-qemu-action@v2
          with:
              image: tonistiigi/binfmt:qemu-v6.2.0
              platforms: linux/amd64,linux/arm64
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build the Docker images
          run: sh build_push_package_github.sh compilers
