FROM alpine:latest
LABEL maintainer="github@vookimedlo.cz"
LABEL homepage="https://github.com/vookimedlo/docker-images"

RUN apk add --no-cache \
    g++                        \
    gcc                        \
    make                       \
    cmake                      \
    git

